# (실습) 넘파이 어레이

**주의사항**

- `None`은 적절한 표현식으로 대체한다.
- `Pass`는 적절한 명령문으로 대체한다.

## numpy 모듈

**문제 1**

아래 코드를 설명하라.

In [1]:
import numpy as np

`코드설명`:

아래 코드는 수정하지 마세요!!!

In [2]:
np.__version__

'1.23.5'

**문제 2**

아래 코드의 기능을 설명하라

In [3]:
np.random.seed(42)

`코드설명`: 코드가 42인 난수 생성

**문제 3**

부동소수점으로 구성된 어레이의 항목은 기본적으로 소수점 이하 8자리까지 출력한다.

In [4]:
Z = np.random.random((40,40))
Z

array([[0.37454012, 0.95071431, 0.73199394, ..., 0.09767211, 0.68423303,
        0.44015249],
       [0.12203823, 0.49517691, 0.03438852, ..., 0.07404465, 0.35846573,
        0.11586906],
       [0.86310343, 0.62329813, 0.33089802, ..., 0.18657006, 0.892559  ,
        0.53934224],
       ...,
       [0.81783422, 0.12020906, 0.5444891 , ..., 0.89803055, 0.2434823 ,
        0.92703454],
       [0.06026739, 0.93443603, 0.35162269, ..., 0.41102847, 0.8398613 ,
        0.90002312],
       [0.35342138, 0.23687056, 0.78052552, ..., 0.07941937, 0.08565825,
        0.89419087]])

`np.set_printoptions()` 의 기능을 다음 두 개의 예를 이용하여 설명하라.

In [5]:
np.set_printoptions(precision=4)

In [6]:
Z

array([[0.3745, 0.9507, 0.732 , ..., 0.0977, 0.6842, 0.4402],
       [0.122 , 0.4952, 0.0344, ..., 0.074 , 0.3585, 0.1159],
       [0.8631, 0.6233, 0.3309, ..., 0.1866, 0.8926, 0.5393],
       ...,
       [0.8178, 0.1202, 0.5445, ..., 0.898 , 0.2435, 0.927 ],
       [0.0603, 0.9344, 0.3516, ..., 0.411 , 0.8399, 0.9   ],
       [0.3534, 0.2369, 0.7805, ..., 0.0794, 0.0857, 0.8942]])

In [7]:
np.set_printoptions(precision=6)

In [8]:
Z

array([[0.37454 , 0.950714, 0.731994, ..., 0.097672, 0.684233, 0.440152],
       [0.122038, 0.495177, 0.034389, ..., 0.074045, 0.358466, 0.115869],
       [0.863103, 0.623298, 0.330898, ..., 0.18657 , 0.892559, 0.539342],
       ...,
       [0.817834, 0.120209, 0.544489, ..., 0.898031, 0.243482, 0.927035],
       [0.060267, 0.934436, 0.351623, ..., 0.411028, 0.839861, 0.900023],
       [0.353421, 0.236871, 0.780526, ..., 0.079419, 0.085658, 0.894191]])

`코드설명`:

아래 코드는 기본 옵션값으로 되돌린다. 수정하지 마세요.

In [ ]:
np.set_printoptions(precision=8)

## 1차원 어레이

**문제 1**

크기가 10이고 모든 항목이 0인 1차원 어레이를
변수 `Z`가 가리키도록 하라.
단, `np.zeros()` 함수를 반드시 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.zeros(10)

Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])).all()

**문제 2**

변수 `Z`가 10에서 49까지의 정수 중에서 짝수로만 구성된 1차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수를 반드시 이용한다.

In [11]:
# None을 적절한 표현식으로 대체하라.
Z = np.arange(10, 50, 2)

Z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

아래 코드는 수정하지 마세요!!!

In [12]:
assert (Z == np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
                        44, 46, 48])).all()

**문제 3**

변수 `Z`가 아래와 같이 선언되었다.

In [13]:
Z = np.array([2, 3, 1, 0, 4])
Z

array([2, 3, 1, 0, 4])

변수 `Z`의 항목을 정렬하라.
단, sort() 메서드를 활용한다.

In [14]:
# None을 적절한 표현식으로 대체하라.
Z.sort()

Z

array([0, 1, 2, 3, 4])

아래 코드는 수정하지 마세요!!!

In [15]:
assert (Z == np.arange(5)).all()

**문제 4**

변수 `Z`가 크기 30이며 무작위로 생성된 1차원 어레이를 가리키도록 하라.
또한 포함된 항목들의 평균값을 계산하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
`np.random.random()` 함수, `mean()` 어레이 메서드를 반드시 이용한다.

In [16]:
# None을 적절한 표현식으로 대체하라.
Z = np.random.random(30)
Z_mean = Z.mean()

Z_mean

0.4618868095723934

아래 코드는 수정하지 마세요!!!

In [17]:
assert (Z.shape == (30,))
print(f"1차원 어레이 평균값: {Z_mean}")

1차원 어레이 평균값: 0.4618868095723934


**문제 5**

1차원 어레이가 다음과 같이 주어졌다.

In [18]:
Z = np.arange(1, 4)

Z

array([1, 2, 3])

(1) 아래 표현식의 계산 결과를 설명하라.

In [19]:
Z*Z

array([1, 4, 9])

`코드설명`: Z의 0값에 위치한 수의 곱, Z의 1값에 위치한 수의 곱, Z의 2값에 위치한 수의 곱

(2) 아래 표현식의 계산 결과를 설명하라.

In [20]:
Z**Z

array([ 1,  4, 27])

`코드설명`: Z의 0값에 위치한 수의 제곱근, Z의 1값에 위치한 수의 제곱근, Z의 2값에 위치한 수의 제곱근

(3) 아래 표현식의 계산 결과를 설명하라.

In [21]:
Z < -Z

array([False, False, False])

`코드설명`: 요소 별로 크기 비교 Z = 1,2,3 이며 -Z = -1,-2,-3

(4) 아래 표현식의 계산 결과를 설명하라.

In [22]:
Z/1/1

array([1., 2., 3.])

`코드설명`: Z에 속해있는 요소 각각 1로 2번 나누기

**문제 6**

변수 `Z`가 아래 모양의 어레이를 가리키도록 하라.
단, `np.linspace()` 함수와 `endpoint` 키워드 인자를 이용한다.

```
[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
```

In [23]:
# None을 적절한 표현식으로 대체하라.
Z = np.linspace(0,0.9,num = 10, endpoint = True)

Z

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

아래 코드는 수정하지 마세요!!!

In [24]:
assert np.isclose(Z, np.array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])).all()

**문제 7**

아래 코드의 실행결과를 설명하라.

In [25]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


`코드설명`: 값 하나당 8바이트, 10x10 행렬이므로 800바이트

**문제 8**

다음 리스트에서 0이 아닌 항목들의 인덱스로 구성된 어레이를 한줄 코드로 생성하라.
단. `np.nonzero()` 함수를 활용한다.

In [26]:
Z = [1, 2, 0, 0, 4, 0]

In [27]:
# None을 적절한 표현식으로 대체하라.

non_zeros = np.nonzero(Z)

non_zeros

(array([0, 1, 4]),)

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (non_zeros == np.array([0, 1, 4])).all()

**문제 9**

두 개의 1차원 어레이가 다음과 같이 주어졌다.

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2

B

array([2., 2., 2.])

아래 코드의 실행 결과를 설명하라.

In [ ]:
(A+B)*(-A/2)

array([-1.5, -1.5, -1.5])

`코드설명`: {(1,1,1) + (2,2,2)} * (-0.5, -0.5, -0.5)

In [ ]:
np.add(A,B,out=B)

array([3., 3., 3.])

`코드설명`: A + B의 값이 기존 B 값을 덮어씌운다

In [ ]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

`코드설명`: A / 2 의 값이 기존 A 값을 덮어씌운다

In [ ]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

`코드설명`: A 에 음수처리하여 A 값을 덮어씌운다.

In [ ]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

`코드설명`: (-0.5, -0.5, -0.5) * (3,3,3) 값이 기존 A 값을 덮어씌운다

## 2차원 어레이

**문제 1**

변수 `Z`가 (5, 5) 모양의 2차원 어레이를 가리키도록 하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
또한 `np.random.random()` 함수를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.random.random((5,5))
Z

array([[0.06817231, 0.02581191, 0.13516629, 0.96311511, 0.54952954],
       [0.96582216, 0.43249788, 0.31181613, 0.50614186, 0.43951169],
       [0.10566468, 0.64082631, 0.21603818, 0.61958795, 0.65020109],
       [0.15202485, 0.06134963, 0.78076159, 0.45980042, 0.0581638 ],
       [0.99486632, 0.05778056, 0.69503523, 0.98367893, 0.2391801 ]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.shape == (5, 5))
assert (Z.dtype == np.float64)

**문제 2**

변수 `Z`가 0에서 8까지의 정수로 이루어진 (3, 3) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수와 `reshape()` 어레이 메서드를 반드시 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.arange(0,9).reshape((3, 3))
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])).all()

**문제 3**

변수 `Z`가 (3, 3) 모양의 2차원 어레이를 가리키도록 하라.
단, 2차원 어레이의 대각선 상은 1이고 나머지는 0이어야 한다.
또한 `np.eye()` 함수를 반드시 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.eye(3)

Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])).all

**문제 4**

변수 `Z`가 아래와 같은 (5,5) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수와 `np.diag()` 함수의 `k` 키워드 인자를 반드시 활용한다.

```
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
```

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.diag(np.arange(1,5), k=-1)

Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0, 0, 0, 0, 0],
                        [1, 0, 0, 0, 0],
                        [0, 2, 0, 0, 0],
                        [0, 0, 3, 0, 0],
                        [0, 0, 0, 4, 0]])).all()

**문제 5**

변수 `Z`가 아래와 같은 (5, 5) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.zeros()` 함수, `np.arange()` 함수, 2차원 어레이 덧셈을 이용한다.

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.zeros((5, 5)) + np.arange(5)

Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.]])).all()

**문제 6**

아래 3x3 단위 행렬에 해당하는 2차원 어레이를 한줄 코드로 생성하라.
단, `np.eye()` 함수를 이용한다.

```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])).all()

**문제 7**

무작위 수로 구성된 (5, 5) 모양의 2차원 어레이가 다음과 같다.

In [ ]:
Z = np.random.random((5, 5))

Z

array([[0.45944677, 0.78501654, 0.89208469, 0.95533469, 0.78690339],
       [0.3154069 , 0.68813471, 0.43760312, 0.25467062, 0.84087158],
       [0.03842635, 0.90176199, 0.46147746, 0.63720148, 0.65935392],
       [0.89511774, 0.63666968, 0.61393358, 0.06665204, 0.51840802],
       [0.150169  , 0.73743377, 0.51222192, 0.68022778, 0.0416729 ]])

변수 `Z`가 가리키는 2차원 어레이에 대해 min-max 크기조정(정규화)을 적용하라.

min-max 크기조정(정규화)은 항목의 모든 값을 아래 식을 통해 0과 1 사이의 부동소수점으로 변환한다. $max$와 $min$은 각각 최대 항목과 최소 항목을 가리킨다.

$$
\frac{x-min}{max - min}
$$

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z_min = Z.min()
Z_max = Z.max()

Z = (Z - Z_min) / (Z_max - Z_min)

Z

array([[0.45917395, 0.81424736, 0.93101819, 1.        , 0.81630519],
       [0.30208096, 0.70858594, 0.4353508 , 0.23584067, 0.87516407],
       [0.        , 0.94157246, 0.46138867, 0.65303706, 0.677197  ],
       [0.9343261 , 0.65245708, 0.6276606 , 0.03078355, 0.52347836],
       [0.12186895, 0.76235256, 0.51673166, 0.69996248, 0.00354076]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.max() == 1 and Z.min() == 0)

## 3차원 어레이

**문제 1**

(1) 변수 `Z`가 (3, 3, 3) 모양의 3차원 어레이를 가리키도록 하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
또한 `np.random.random()` 함수를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.random.random((3,3,3))

Z

array([[[0.61501297, 0.77463378, 0.64390425],
        [0.53030213, 0.04195122, 0.96848878],
        [0.79871419, 0.29282204, 0.97997033]],

       [[0.60188159, 0.58242266, 0.74807318],
        [0.81176979, 0.65647861, 0.12809575],
        [0.33826751, 0.92808364, 0.22461561]],

       [[0.37216702, 0.43207688, 0.43940499],
        [0.61293958, 0.94307584, 0.24069271],
        [0.12150138, 0.19747049, 0.8869249 ]]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.shape == (3, 3, 3))
assert (Z.dtype == 'f8')

(2) `Z`에 포함된 항목들 중에서 최댓값과 최솟값의 차이를 구하라.
단, `maximum`, `mininum` 두 변수가 각각 최댓값과 최솟값을 가리키도록 하며,
`max()`와 `min()` 어레이 메서드를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
maximum = Z.max()
minimum = Z.min()

maximum - minimum

0.9380191059272144

아래 코드는 수정하지 마세요!!!

In [ ]:
print(f"최댓값과 최솟값의 차이: {maximum - minimum}")

최댓값과 최솟값의 차이: 0.9380191059272144


## `dtype` 종류

**문제 1**

아래 두 코드의 실행결과를 설명하라.

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


`코드설명`: 각 인트 타입 별 최솟값 및 최댓값 출력

In [ ]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


`코드설명`: 각 float 별 최댓값, 최솟값, 머신 엡실론 값 출력

**문제 2**

부동소수점으로 구성된 1차원 어레이가 아래와 같이 주어졌다.

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)

Z

array([72.84907  , 77.644745 , 65.61618  , 17.742876 , 54.502693 ,
       98.46697  , 93.73881  ,  4.3173738, 16.481482 , 13.172877 ],
      dtype=float32)

변수 `Y`가 변수 `Z`가 가리키는 1차원 어레이의 dtype이 `int32`로 형변환된 1차원 어레이를 가리키도록 하라.
단, `astype()` 메서드를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Y = Z.astype(np.int32)

Y

array([72, 77, 65, 17, 54, 98, 93,  4, 16, 13], dtype=int32)

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y.shape == (10,))
assert (Y.dtype == np.int32)

**문제 3**

변수 `Z`가 아래와 같이 무작위로 생성된 길이가 10인 1차원 어레이를 가리킨다.

In [ ]:
Z = np.random.uniform(0,10,10)
Z

array([7.2597991 , 8.1778533 , 2.13511366, 5.05852693, 8.40703028,
       7.32801545, 5.42237205, 5.9034769 , 5.08360547, 2.97548451])

(1) 나머지 연산자(`%`)를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Y = Z.astype(int)

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()

(2) 몫 연산자(`//`)를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Y = Z // 1

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()

(3) 내림 함수 `np.floor()` 함수를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Y = np.floor(Z)

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()

(4) `np.trunc()` 함수를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Y = np.trunc(Z)

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()